### PR TITLE
Indonesia translation

### PR DESCRIPTION
**Pull request by ganjarsetia**
Add Indonesian translations.

### CODE REVIEW

**Comment by antonkarliner** [comment]
Hello, @ganjarsetia! Thanks a lot for your efforts! Do you think you can also translate recipes for other methods? In order to provide users with best experience, it would be better to make all the recipes available in their language. I could do it myself using automated translation, but it would probably take more time and as a native speaker you would definitely make the translation much better :) Again, thanks a lot for a great contribution!

**Comment by ganjarsetia** [comment]
> Hello, @ganjarsetia! Thanks a lot for your efforts! Do you think you can also translate recipes for other methods? In order to provide users with best experience, it would be better to make all the recipes available in their language. I could do it myself using automated translation, but it would probably take more time and as a native speaker you would definitely make the translation much better :) Again, thanks a lot for a great contribution!

@antonkarliner  Yes of course, that's why I put `WIP (work in progress)`. There is a lot words to translate :smile: and I translate it without running the app locally, because I'm not install Flutter in my laptop.

Btw I have question. See this https://youtu.be/v8pL6vSuL_I?t=56 

image

Do you think the current app can use those variables in Tetsu Katsuya 4:6 method?

**Comment by antonkarliner** [comment]
@ganjarsetia great, then I will wait for all files to be translated and then I'll be sure to test it thoroughly. Regarding your question about Tetsu Katsuya 4:6 method, I think at this stage this would be an overkill to integrate such complicated logic, but I will keep it in mind for the future. Thanks for the interesting video!

**Comment by ganjarsetia** [comment]
@antonkarliner In the contribution section, I haven't write my name. Is it okay if I write it with my paypal link?

Maybe something like

```plain
Ganjar Setia - helped to improve Indonesian translation. You can support him [Donation](https://paypal.com/)
```

**Comment by antonkarliner** [comment]
@ganjarsetia hey! First of all, thanks for your contribution, great work!

Regarding your paypal question... well, it's quite tricky, actually for a couple of reasons:
1. It feels like this may be a little unfair to other contributors.
2. More importantly, Apple will reject a release with links to external payment services. Trust me, I've got some experience with it.

So, I think the optimal solution will be to include a link to your page (website, Github, etc), where you can add any donation links that you like. 

Again, thanks for your work, can't wait to test and release it!

**Comment by ganjarsetia** [comment]
> @ganjarsetia hey! First of all, thanks for your contribution, great work!
> 
> Regarding your paypal question... well, it's quite tricky, actually for a couple of reasons:
> 
> 1. It feels like this may be a little unfair to other contributors.
> 2. More importantly, Apple will reject a release with links to external payment services. Trust me, I've got some experience with it.
> 
> So, I think the optimal solution will be to include a link to your page (website, Github, etc), where you can add any donation links that you like.
> 
> Again, thanks for your work, can't wait to test and release it!

@antonkarliner I see. I think it's not my right to write myself on `CONTRIBUTORS.md`. It's all yours.

I hope it can be released soon!

FYI, my name is Ganjar Setia from Indonesia, and here my github https://github.com/ganjarsetia

**Comment by ganjarsetia** [comment]
@antonkarliner Dont merge it yet, something is wrong.

Look at this https://github.com/antonkarliner/timer-coffee/blob/a759821bd9a6770a2a111bb3800c0480c8ca7c1d/assets/data/en/recipes_aeropress.json#L115

Why add whitespace in front of description, is there any purpose or typo ?

**Comment by antonkarliner** [comment]
> Why add whitespace in the text, is there any purpose or typo ?

Hey! Seems that it's a typo. Thanks, will fix!

**Pull request merged**
